/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author talha
 */
public class not extends javax.swing.JFrame {
static int i=0;
    /**
     * Creates new form not
     */
    public not() {
        initComponents();
    }
static public void goster() {
    String dizi[]=new String[50];
    try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection bag=DriverManager.getConnection("jdbc:mysql://localhost:3306/calisandb","root", "");

    String sql="SELECT * FROM notlar";

    PreparedStatement p1=bag.prepareStatement(sql);


            ResultSet sonuc=p1.executeQuery();

             i=0;
            int test=0;
            
            while(sonuc.next() ) {
                
                dizi[i]=sonuc.getString(1);
                dizi[i]+="    ";
                dizi[i]+=sonuc.getString(2);
                dizi[i]+="    ";
                dizi[i]+=sonuc.getString(3);
                dizi[i]+="    ";
                dizi[i]+=sonuc.getString(4);

                
                        
                       i++;
            }
            
            
            list1.setListData(dizi);

            p1.close();
            bag.close();
            

}
catch(Exception e) {
    System.out.println(e.getMessage());
}
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list3 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        buton3 = new javax.swing.JButton();
        text4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Not");

        jLabel1.setText("Öğrenci Adı");

        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Not");

        text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text3ActionPerformed(evt);
            }
        });

        jButton1.setText("NOT EKLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list1);

        jLabel3.setText("Ders ");

        jScrollPane2.setViewportView(list2);

        jButton2.setText("NOT GÜNCELLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(list3);

        jLabel4.setText("ID");

        jLabel5.setText("İSİM");

        jLabel6.setText("DERS");

        jLabel7.setText("NOT");
        jLabel7.setToolTipText("");

        jLabel8.setText("ID");

        jLabel9.setText("İSİM");

        jLabel10.setText("Öğrenci Numara");

        jLabel11.setText("ID");

        jLabel12.setText("DERS");

        buton3.setText("NOT ORTALAMASI");
        buton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("ORTALAMA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(86, 86, 86)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(text1)
                            .addComponent(text2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buton3)
                        .addGap(52, 52, 52)
                        .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(buton3)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         

        Connection bag=null;
        PreparedStatement p1=null;
        
        try {
            if( ((Integer.parseInt(text3.getText())<0) || Integer.parseInt(text3.getText())>100) ){
           JOptionPane.showMessageDialog(null, "GİRECEĞİNİZ NOT ARALIĞI 0-100 ARASINDA OLMALIDIR.");
           throw new Exception();
       }
            Class.forName("com.mysql.jdbc.Driver");

                 bag=DriverManager.getConnection("jdbc:mysql://localhost:3306/calisandb","root", "");
                  String sql="select ogrAd from ogrenci where ogrAd=?";
      p1=bag.prepareStatement(sql);
     p1.setString(1, text1.getText());
     ResultSet r1=p1.executeQuery();
     if(r1.next()) {
         
     }
     else {
         JOptionPane.showMessageDialog(null, "GİRDİĞİNİZ ÖĞRENCİ ADI BULUNMAMAKTADIR.");
         throw new Exception();
     }
     
        sql="select dersAd from dersler where dersAd=?";
      p1=bag.prepareStatement(sql);
     p1.setString(1, text2.getText());
     r1=p1.executeQuery();
     if(r1.next()) {
         
     }
     else {
         JOptionPane.showMessageDialog(null, "GİRMİŞ OLDUĞUNUZ DERS LİSTEDE BULUNMAMAKTADIR.");
         throw new Exception();
     }           
     
             sql="INSERT INTO notlar(ID,ogrAd,ogrDers,ogrNot) VALUES(?,?,?,?)";
            
             p1=bag.prepareStatement(sql);
            p1.setString(1, String.valueOf(i+1));
            p1.setString(2, text1.getText());
            p1.setString(3, text2.getText());
            p1.setString(4, text3.getText());
            
           
                        p1.executeUpdate();

            
            
                goster();

        }
        catch(Exception e) {
            System.out.println(e.getMessage());
        }
        finally {
            try {
                p1.close();
            bag.close();
            }
            catch(Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Connection bag=null;
 PreparedStatement p1=null;
        
        try {
            if( ((Integer.parseInt(text3.getText())<0) || Integer.parseInt(text3.getText())>100) ){
           JOptionPane.showMessageDialog(null, "GİRECEĞİNİZ NOT ARALIĞI 0-100 ARASINDA OLMALIDIR.");
           throw new Exception();
       }
    Class.forName("com.mysql.jdbc.Driver");

     bag=DriverManager.getConnection("jdbc:mysql://localhost:3306/calisandb","root", "");
  
    
    
    String sql="UPDATE notlar SET ogrNot=? WHERE ogrAd=? and ogrDers=?";

    p1=bag.prepareStatement(sql);

            p1.setString(1,text3.getText() );
            p1.setString(2,text1.getText());
            p1.setString(3,text2.getText());
            
            int sonuc=p1.executeUpdate();
            if(sonuc!=1) 
                JOptionPane.showMessageDialog(null, "GÜNCELLEME GERÇEKLEŞMEDİ, ÖĞRENCİ ADINI VE DERSİ KONTROL EDİNİZ.");
    goster();
}
catch(Exception e) {
    System.out.println(e.getMessage());
}
        finally {
            try {
                  p1.close();
            bag.close();
            }
            catch(Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton3ActionPerformed
        try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection bag=DriverManager.getConnection("jdbc:mysql://localhost:3306/calisandb","root", "");
double toplam=0;
    String sql="SELECT * FROM notlar WHERE ogrAd=?";

    PreparedStatement p1=bag.prepareStatement(sql);
            
    p1.setString(1, text1.getText());

            ResultSet sonuc=p1.executeQuery();

            int b=0;
            while(sonuc.next()) {
               toplam+=(Integer.valueOf(sonuc.getString(4)));
             
                
                b++;
            }
            
            
              text4.setText(String.valueOf(toplam/b));
              
                       
            
            p1.close();
            bag.close();
            

}
catch(Exception e) {
    System.out.println(e.getMessage());
}
        
        
        
    }//GEN-LAST:event_buton3ActionPerformed
    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
  
    }//GEN-LAST:event_text1ActionPerformed
    private void text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text3ActionPerformed
     
    }//GEN-LAST:event_text3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(not.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(not.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(not.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(not.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new not().setVisible(true);
            }
        });
        
        
        
         goster();
        list2.setListData(ogrenci.goster());
         list3.setListData(ders.goster());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JList<String> list1;
    private static javax.swing.JList<String> list2;
    private static javax.swing.JList<String> list3;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    // End of variables declaration//GEN-END:variables
}
